[package]
name = "common-pipeline-sources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[package.metadata.cargo-machete]
ignored = ["xml-rs"]

[dependencies]
async-channel = "1.7.1"
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-compress = { path = "../../../common/compress" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-formats = { path = "../../formats" }
common-io = { path = "../../../common/io" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../core" }
common-settings = { path = "../../settings" }
common-storage = { path = "../../../common/storage" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
bstr = "1.0.1"
crossbeam-channel = "0.5.6"
csv-core = "0.1.10"
dashmap = "5.4.0"
futures = "0.3.24"
futures-util = "0.3.24"
opendal = { workspace = true }
parking_lot = "0.12.1"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1.36"
typetag = "0.2.3"
xml-rs = "0.8.14"
